package org.ml4j.nn.components;

public enum DirectedComponentType {
	COMPONENT_CHAIN, COMPONENT_BATCH, COMPONENT_CHAIN_BATCH, COMPONENT_CHAIN_GRAPH, AXONS, AXONS_CHAIN, AXONS_GRAPH,
	SYNAPSES, SYNAPSES_CHAIN, SYNAPSES_GRAPH, LAYER, LAYER_CHAIN, NETWORK, ACTIVATION_FUNCTION,
	ONE_TO_MANY, MANY_TO_ONE, CUSTOM;
}
