package org.ml4j.nn.components;

public interface DirectedComponent<I, A extends DirectedComponentActivation<I, ?>, C>
		extends NeuralNetworkComponent {

	/**
	 * Forward Propagates the activations through the Synapses via the Axons and
	 * DifferentiableActivationFunction.
	 * 
	 * @param input
	 *            The input to the DirectedSynapses
	 * @param synapsesContext
	 *            The context within which we forward propagate the activations
	 * @return A DirectedSynapsesActivation encapsulating the artifacts generated by
	 *         this forward propagation - including the NeuronsActivation output
	 *         from the right hand side of these DirectedSynapses.
	 */
	A forwardPropagate(I input, C context);
	
}
