/*
 * Copyright 2019 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
package org.ml4j.nn.components.manytomany;

import java.util.List;

import org.ml4j.nn.components.ChainableDirectedComponentActivation;
import org.ml4j.nn.components.onetone.DefaultDirectedComponentChainActivation;
import org.ml4j.nn.neurons.NeuronsActivation;

/**
 * Interface for an activation from a DefaultDirectedComponentChainBatch
 * instance.
 * 
 * @author Michael Lavelle
 *
 */
public interface DefaultDirectedComponentChainBatchActivation
		extends ChainableDirectedComponentActivation<List<NeuronsActivation>> {

	/**
	 * @return A list of the DefaultDirectedComponentChainActivation instances generated by
	 * each parallel chain in the batch.
	 */
	List<DefaultDirectedComponentChainActivation> getActivations();

	/**
	 * @return A list of the output NeuronsActivation instances generated by each parallel
	 * chain in the batch.
	 */
	List<NeuronsActivation> getOutput();
}
